# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# -------------------
# RUN PSAKE SCRIPT
# -------------------
   
- task: BatchScript@1
  inputs:
    filename: .\psake.cmd
  displayName: Run Abbreviated PSAKE Build for Feature Work

# -------------------
# PIPELINE FOLLOW-UP
# -------------------

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Build.SourcesDirectory)\src\BulkWriter.Tests\TestResults\*.xml'
  condition: succeededOrFailed()
  displayName: Publish Test Results to Pipeline
