# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    - '*-deploy'

pr:
- 'master'

pool:
  vmImage: 'windows-latest'

steps:
# -------------------
# Install Dependencies
# -------------------
- task: PowerShell@2
  inputs:
    targetType: inline
    script: $(Build.SourcesDirectory)/setup.ps1
  displayName: Install Dependencies for Feature Work

- task: NuGetCommand@2
  displayName: 'Authenticate with NuGet feed'
  inputs:
   command: custom
   feedsToUse: config
   arguments: sources update -Name "$(bulkwriterfeed)" -Username "bulkWriter" -Password "$(bulkwriterfeedpassword)" -StorePasswordInClearText -ConfigFile nuget.config

# -------------------
# RUN PSAKE SCRIPT
# -------------------
   
- task: BatchScript@1
  inputs:
    filename: .\psake.cmd
    arguments: 'Run-CI'
  displayName: Run Abbreviated PSAKE Build for Feature Work

# -------------------
# PIPELINE FOLLOW-UP
# -------------------

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Build.SourcesDirectory)/src/BulkWriter.Tests/TestResults/*.xml'
  displayName: Publish Test Results to Pipeline

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/src/BulkWriter/BulkWriter.csproj'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Create Nuget Package

- task: DotNetCoreCLI@2
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: '$(bulkwriterfeed)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Push Package to Private Feed

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGetConnnection'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: Push Package to Nuget