# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
- 'development'
- 'master'

pool:
  vmImage: 'windows-latest'

steps:
# -------------------
# Install Dependencies
# -------------------
- task: UseDotNet@2
  displayName: Require .NET 2.1
  inputs:
    packageType: 'runtime'
    version: '2.1.x'

- task: UseDotNet@2
  displayName: Require .NET 3.1 SDK for Build Process
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetCommand@2
  displayName: 'Authenticate with NuGet feed'
  inputs:
   command: custom
   feedsToUse: config
   arguments: sources update -Name "$(bulkwriterfeed)" -Username "bulkWriter" -Password "$(bulkwriterfeedpassword)" -StorePasswordInClearText -ConfigFile nuget.config

- task: PowerShell@2
  displayName: Setup Required Dependencies
  inputs:
    filePath: 'setup.ps1'

- task: PowerShell@2
  displayName: Generate Version using GitVersion
  inputs:
    targetType: 'inline'
    script: dotnet gitversion /output buildserver

# -------------------
# RUN PSAKE SCRIPT
# -------------------

- task: PowerShell@2
  displayName: Build and Test
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      invoke-psake run-ci -properties @{'version'='$(Build.BuildNumber)'}

# -------------------
# PIPELINE FOLLOW-UP
# -------------------

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Build.SourcesDirectory)/src/BulkWriter.Tests/TestResults/*.xml'
  displayName: Publish Test Results to Pipeline

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/src/BulkWriter/BulkWriter.csproj'
  #condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
  displayName: Create Nuget Package


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifact: 'package'
    publishLocation: 'pipeline'

- task: DotNetCoreCLI@2
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedPublish: '$(bulkwriterfeed)'
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Push Package to Private Feed